### ISSUE TITLE
Can you please disallow the posting of memes, dumb images, and too many words from safe for neets?

### ISSUE THREAD

**Issue by hortanz** [kenneththomas/cechat-politica#31]
Safe for neets is not an enjoyable experience because of the combination of memes, dumb images and animations, and too many words. It would increase the quality if these things were disallowed.

P.S. please punish Zithers *and Prosh* for acting out when tagged in the jongaz role.

* denotes edit

**Comment by kenneththomas** [comment]
how bout 2 sfn channels. keep the one as it is now as a gross free for all. new one with quality material only

different access roles

**Comment by hortanz** [comment]
yes thank you very much kenneththomas

**Comment by Pwnlamesa** [comment]
we can call it safe for newts

**Comment by kenneththomas** [comment]
"safe-for-newts" has been created
the role for access is known as "newt-club"

there will be a 2 week introductory period where the following rules apply:
- "safe-for-newts" is open for those who are currently in "nsfw-access", after this period ends, only "newt-club" will retain access
- any participation in safe-for-newts will grant the "newt-club" role unless requested otherwise
- you may request an admin, without a ticket, to add/remove "nsfw-access" or "newt-club" roles from your profile

prosh and zithers now have read only access to john chat
